### ISSUE TITLE
feat: Add ~boop (mention), and ~pat (mention)

### ISSUE THREAD

**Issue by Ilovemyhous** [thetayloredman/ProtoBot#172]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when (...)
No problems.

**Describe the solution you'd like**
H-Hello!!11 I think, i-it w-wouwd be nice t-to add `~boop (mention)`, and `~pat (mention)`, t-to the x3 bot.
Thanks in advance!
OwO

**Describe alternatives you've considered**
The bot already really nice like that, so adding those two would make it better.

**Additional context**
The OwOner wanted me to create the issue.
![image](https://user-images.githubusercontent.com/50217071/111052198-57819d00-8459-11eb-8de6-cbef39ad1bd1.png)

**Maintainer Edit:** Yes, I'm okay with an uwuified issue today.

**Comment by thetayloredman** [comment]
Original:

> Hello! I think, it would be nice to add ~boop (mention), and ~pat (mention), to the bot.
> Thanks in advance!
> OwO

**Comment by thetayloredman** [comment]
Implemented in 4b3cd497935e9ac91cb77df6114446f202be74e7.

Patches:
- `[PATCH 1/3]` 701263638235f0e930b539b0f5323274d13fc978: `fix(boop): fix broken emote in boop` - `thetayloredman` **CI: OK**
- `[PATCH 2/3]` 56193459544f7c5e5d0aebe576ca077c95821264: `fix(boop): remove other broken emote` - `thetayloredman` **CI: OK**
- `[PATCH 3/3]` 5eac45ef32391dc681b7a2ecce6acf19d2a25bcb: `fix(pat): remove boop emote` - `thetayloredman` **CI: OK**
