### ISSUE TITLE
repo: use Husky on-commit hooks again

### ISSUE THREAD

**Issue by thetayloredman** [thetayloredman/ProtoBot#480]
...to ensure the repo is not failing the prettier check so often.

**Comment by thetayloredman** [comment]
[Husky docs](https://typicode.github.io/husky/#/)

**Comment by thetayloredman** [comment]
also see [commitlint by conventional-commits, which we follow](https://www.freecodecamp.org/news/how-to-use-commitlint-to-write-good-commit-messages/), likely very important to keep *ahem* @ilikestohack from writing trashy commit names

**Comment by thetayloredman** [comment]
turns out you saw that

@ilikestohack do you have any debate against this?

**Comment by ilikestohack** [comment]
> turns out you saw that
> 
> @ilikestohack do you have any debate against this?

I would like to bring upon the point that I'm a lazy dev and when noone else is seeing my code that is really going to care anyways do I really need to spend 5 minutes typing out a commit message when I can just say added this changed that lol

**Comment by thetayloredman** [comment]
> > turns out you saw that
> > 
> > @ilikestohack do you have any debate against this?
> 
> I would like to bring upon the point that I'm a lazy dev and when noone else is seeing my code that is really going to care anyways do I really need to spend 5 minutes typing out a commit message when I can just say added this changed that lol

but... it doesnt take 5 minutes to type `feat:` before your message...

also people do look at commits on open source projects

also future employers care:tm:

**Comment by thetayloredman** [comment]
Triaged HIGH due to @ilikestohack existance

**Comment by thetayloredman** [comment]
note to self: do not add @ilikestohack to this repo or to a review on this pr
