### ISSUE TITLE
[BUG] The bot isn't banned

### ISSUE THREAD

**Issue by ada-mon** [thetayloredman/ProtoBot#63]
**Describe the bug**
The bot isn't banned.

**To Reproduce**
1. Look at bot
2. See bot isn't banned

**Expected behavior**
The bot shouldn't be anywhere because it should be banned. 

**Actual Behavior**
The bot continues to exist.

**Screenshots**
![imgur.com/a/dQX2YUK](https://i.imgur.com/oyFUore.jpeg) 

**Additional context**
![https://imgur.com/a/nFaty2Q](https://i.imgur.com/pugLhv1.jpeg) 

**Mod Edit**: embed screenshots instead of links

**Comment by thetayloredman** [comment]
![ante in a nutshell](https://drago.is-inside.me/tVl07mVn.png)

**Comment by thetayloredman** [comment]
I would close this as invalid, but it'll stay here for now 😉
