### ISSUE TITLE
[FEATURE] Delete user's message for hug command

### ISSUE THREAD

**Issue by ada-mon** [thetayloredman/ProtoBot#64]
**Is your feature request related to a problem? Please describe.**
The hug command should delete the user's message, like the smite command.

**Describe the solution you'd like**
The message? Delete it.

**Describe alternatives you've considered**
There are no alternatives. Messages must die.

**Comment by thetayloredman** [comment]
KILL THE MESSAGES 🔪

**Comment by thetayloredman** [comment]
Branch: `feat/aff-del-msg`
