### ISSUE TITLE
[BUG] ~uwuify runs with 2000+ char text

### ISSUE THREAD

**Issue by thetayloredman** [thetayloredman/ProtoBot#97]
**Describe the bug**
~uwuify can result in long text, causing errors.

**To Reproduce**

1. Run '`~uwuify ~uwuify u check for length  did u check for length  did u check for length  did u check for length  did u check for length  did u check for length u check for length  did u check for length  did u check for length  did u check for length  did u check for length  did u check for length ~uwuify u check for length  did u check for length  did u check for length  did u check for length  did u check for length  did u check for length u check for length  did u check for length  did u check for length  did u check for length  did u check for length  did u check for length ~uwuify u check for length  did u check for length  did u check for length  did u check for length  did u check for length  did u check for length u check for length  did u check for length  did u check for length  did u check for length  did u check for length  did u check for length ~uwuify u check for length  did u check for length  did u check for length  did u check for length  did u check for length  did u check for length u check for length  did u check for length  did u check for length  did u check for length  did u check for length  did u check for length ~uwuify u check for length  did u check for length  did u check for length  did u check for length  did u check for length  did u check for length u check for length  did u check for length  did u check for length  did u check for length  did u check for length  did u check for length ~uwuify u check for length  did u check for length  did u check for length  did u check for length  did u check for length  did u check for length u check for length  did u check for length  did u check for length  did u check for length  did u check for length  did u check for length`'
2. See error

**Expected behavior**
The bot gives a warning or splits the text

**Actual Behavior**
Errors

**Screenshots**
None

**Additional context**
@Shadowplays4k reported this

**Comment by LostNuke** [comment]
Wouldnt this be resolved with #98 too?

**Comment by thetayloredman** [comment]
Nope, the `*action interjections*` can also cause a problem

**Comment by Alcremie** [comment]
The easiest thing would be to just trim the first `2000 - 15` characters from the uwuified, accounting for the leading `Uwuified text: `, which seems like the best solution to me.

**Comment by thetayloredman** [comment]
> The easiest thing would be to just trim the first `2000 - 15` characters from the uwuified, accounting for the leading `Uwuified text: `, which seems like the best solution to me.

`Uwuified text: ` was removed as of #98

**Comment by Alcremie** [comment]
Well, from there, only send the first 2000 characters, then, or the first 1997 + `...` if you want to show that the output exceeded the maximum message length.

**Comment by LostNuke** [comment]
I don't know I think if it exceeds the char limit, we should either split it or just give out a message saying that there are too many chars. Just removing some of it would be rather meh. I'd say split prolly the best way to put it

**Comment by thetayloredman** [comment]
Wouldn't be that hard to implement, @LostNuke take a look at `TextChannel#send()` in the `options` parameter and PR it!
